apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: bank:latest
          imagePullPolicy: Never
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "postgres"
            - name: DB_URL
              value: "database-statefulset-0.database-service.default.svc.cluster.local"
            - name: DB_NAME
              value: "deposit"
  selector:
    matchLabels:
      app: bank
